### ISSUE TITLE
macos/ios support ? 

### ISSUE THREAD

**Issue by treememory** [maelaubert/VulkanSift#3]
Thank you very much for your excellent work on this project; the results are impressive. I am curious if there are any plans to adapt the project for macOS/iOS platforms, possibly utilizing MoltenVK. Additionally, I encountered some configuration issues on an AMD GPU. Is this algorithm universally adaptable across different platforms, including those with AMD GPUs? Any guidance or information regarding this would be greatly appreciated.

**Comment by maelaubert** [comment]
Hey!

> I am curious if there are any plans to adapt the project for macOS/iOS platforms, possibly utilizing MoltenVK

I haven't pushed any improvement to this project in a while, but I think adding support for building with MoltenVK (at least when installed as part of the VulkanSDK on MacOS) would make a lot of sense. I actually might look into that and some other improvements in the next few days 

> Additionally, I encountered some configuration issues on an AMD GPU. Is this algorithm universally adaptable across different platforms, including those with AMD GPUs?

Assuming your GPU support Vulkan you should be able to use this library without too much trouble. But of course there's a limited set of hardware I could try it on and some devices may show new errors so any feedback and error you can report would help!

**Comment by treememory** [comment]
Thank you very much for your support! I am currently looking to evaluate the performance of different feature extraction methods on various platforms such as iPhones, Android devices, and FPGAs. While ORB features are fast, their robustness is limited, and while methods like SuperPoint offer better results, they don't meet real-time requirements. The feature extraction performance on the computer side, as you presented, is very impressive. I'm interested in leveraging your project to experiment with SIFT feature extraction on mobile devices.

Do you think your project could support platforms like iPhones? Compared to other more established SIFT extraction methods, integrating your solution could introduce some unique advantages, potentially broadening the application scope and garnering more attention.

Thank you again for your support!

**Comment by maelaubert** [comment]
I added the support for MoltenVK in 7c01bd9 so you should be able to get it running on MacOS easily with the Vulkan SDK installed.

> Do you think your project could support platforms like iPhones?

With this addition the current code should support iOS but I won't be able to support that myself since I don't have a personal hardware to test that on a real device. Apart from build system issues the main source of trouble is probably going to be the packaging MoltenVK within the iOS application, the MoltenVK documentation has some information on how to do that with XCode: https://github.com/KhronosGroup/MoltenVK/blob/main/Docs/MoltenVK_Runtime_UserGuide.md#install-moltenvk-as-a-dynamic-library

**Comment by treememory** [comment]
I'm immensely grateful for your work. The latest version has been successfully deployed on a Mac mini (M2), demonstrating rapid image processing capabilities. For a 640x480 image with rich texture, it impressively extracts over 2000 points in about 11.5ms, and for less textured images, around 700 points in roughly 8ms. With minor modifications, this was also adapted to run on iOS, specifically tested on an iPhone 11 (A13 GPU), where the respective processing times were 46.0ms and 40.3ms. I deeply appreciate your efforts; they are truly remarkable.

In practical usage, the algorithm autonomously extracts features from an input image, but the specific number of features varies. Is there a way to manually set a limit on the number of extracted points, for instance, capping it to the top 500 features? I haven’t found any specific parameter settings for this. Does our system support such customization?

**Comment by treememory** [comment]
When comparing the SIFT feature extraction (extracting 800 points) in OpenCV, it's noted that on the Mac platform, OpenCV typically takes around 24ms, whereas on the iOS platform, it averages about 47.6ms. This suggests a significant speed increase of nearly double on the Mac platform, while the performance on iOS remains relatively unchanged. Intuitively, one might expect that using the GPU on iOS would be faster than the CPU. Possible reasons for this could include differences in hardware optimization, the efficiency of the GPU utilization in the algorithm, or the specific architectural features of the iOS devices. Further investigation into these aspects might provide more clarity.

**Comment by maelaubert** [comment]
I'm glad you got it working on iOS!

> Is there a way to manually set a limit on the number of extracted points, for instance, capping it to the top 500 features? I haven’t found any specific parameter settings for this. Does our system support such customization?

VulkanSift doesn't really support that. You can only set `max_nb_sift_per_buffer` in the `vksift_Config` to limit the number of features extracted but I wouldn't recomment to use that.

If you want the get the N best features I would recommend to sort the features yourself on the CPU after getting the detection results, you could do something similar to what OpenCV is doing and sort them using the absolute DoG image intensity at the feature position (you have that in `vksift_Feature::intensity`)

**Comment by maelaubert** [comment]
Closing this issue since the initial problem (MacOS/iOS support) appears to be solved. Feel free to open a new ones as needed!
